// name : 
// id no:
package cryptoproj;

public class HomePage extends javax.swing.JFrame {

    /** 
     * Creates new form HomePage
     */
    public HomePage() {
        initComponents();
    }
    public HomePage(NoobChain n) {
        initComponents();
        nc=n;
        evi_no=0;
        evi_det="";
        loc="";
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        MineBlockButton = new javax.swing.JButton();
        AddEvidence = new javax.swing.JButton();
        viewUserButton = new javax.swing.JButton();
        output = new javax.swing.JLabel();
        SubmissionLoc = new javax.swing.JTextField();
        evi_num = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        evi_info = new javax.swing.JTextField();
        minehash = new javax.swing.JTextField();
        logout = new javax.swing.JButton();
        backgroung = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Submission Location  :");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(30, 50, 180, 30);

        MineBlockButton.setBackground(new java.awt.Color(0, 0, 0));
        MineBlockButton.setFont(new java.awt.Font("DialogInput", 1, 14)); // NOI18N
        MineBlockButton.setForeground(new java.awt.Color(255, 255, 255));
        MineBlockButton.setText("MINE BLOCK");
        MineBlockButton.setBorderPainted(false);
        MineBlockButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MineBlockButtonActionPerformed(evt);
            }
        });
        jPanel1.add(MineBlockButton);
        MineBlockButton.setBounds(50, 460, 130, 50);

        AddEvidence.setBackground(new java.awt.Color(0, 0, 0));
        AddEvidence.setFont(new java.awt.Font("DialogInput", 1, 14)); // NOI18N
        AddEvidence.setForeground(new java.awt.Color(255, 255, 255));
        AddEvidence.setText("ADD EVIDENCE");
        AddEvidence.setBorderPainted(false);
        AddEvidence.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddEvidenceActionPerformed(evt);
            }
        });
        jPanel1.add(AddEvidence);
        AddEvidence.setBounds(410, 290, 160, 50);

        viewUserButton.setBackground(new java.awt.Color(0, 0, 0));
        viewUserButton.setFont(new java.awt.Font("DialogInput", 1, 14)); // NOI18N
        viewUserButton.setForeground(new java.awt.Color(255, 255, 255));
        viewUserButton.setText("VIEW USER");
        viewUserButton.setBorderPainted(false);
        viewUserButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewUserButtonActionPerformed(evt);
            }
        });
        jPanel1.add(viewUserButton);
        viewUserButton.setBounds(230, 460, 120, 50);

        output.setForeground(new java.awt.Color(255, 255, 255));
        output.setText("ALL DETAILS ABOVE ARE MANDATORY TO ADD EVIDENCE");
        jPanel1.add(output);
        output.setBounds(10, 260, 360, 30);

        SubmissionLoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmissionLocActionPerformed(evt);
            }
        });
        jPanel1.add(SubmissionLoc);
        SubmissionLoc.setBounds(240, 50, 340, 40);

        evi_num.setText("0");
        evi_num.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                evi_numActionPerformed(evt);
            }
        });
        jPanel1.add(evi_num);
        evi_num.setBounds(240, 110, 340, 40);

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Evidence Number   :");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(30, 110, 180, 40);

        jLabel4.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Evidence  details      :");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(20, 180, 180, 50);

        evi_info.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                evi_infoActionPerformed(evt);
            }
        });
        jPanel1.add(evi_info);
        evi_info.setBounds(240, 190, 340, 60);

        minehash.setBackground(new java.awt.Color(0, 0, 0));
        minehash.setFont(new java.awt.Font("Lucida Console", 1, 11)); // NOI18N
        minehash.setForeground(new java.awt.Color(255, 255, 255));
        minehash.setText("MINED VAlUE");
        jPanel1.add(minehash);
        minehash.setBounds(30, 390, 590, 50);

        logout.setBackground(new java.awt.Color(0, 0, 0));
        logout.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        logout.setForeground(new java.awt.Color(255, 0, 51));
        logout.setText("LOG OUT");
        logout.setBorderPainted(false);
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });
        jPanel1.add(logout);
        logout.setBounds(430, 460, 140, 50);

        backgroung.setIcon(new javax.swing.ImageIcon("C:\\Users\\M SREINIVAS REDDY\\Desktop\\crytpo8.jpg")); // NOI18N
        jPanel1.add(backgroung);
        backgroung.setBounds(0, 0, 640, 540);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 640, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 536, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>                        

    private void evi_numActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
        evi_no = Integer.parseInt(evi_num.getText());
    }                                       

    private void AddEvidenceActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
        String a = evi_num.getText();
        if(a.equals(""))
        {
            minehash.setText("Please enter all values");
        }
        else
        {
            evi_no = Integer.parseInt(evi_num.getText());
            loc=SubmissionLoc.getText();
            evi_det = evi_info.getText();
            System.out.println("\nloc : "+loc);
            System.out.println("\nevi_det : "+evi_det);
            if(!evi_det.equals("")&&evi_no != 0&&!loc.equals(""))    
            {
                for(int i=0;i<nc.blockchain.size();i++)
                {
                    prev_hash = nc.blockchain.get(i).previousHash;
                }
                nc.createBlock(evi_no,nc.currentUser,loc,prev_hash,evi_det); 
                this.setVisible(false);
            }
            else
            {
                System.out.println("".equals("loc== emoty  "+ loc));
                minehash.setText("Please enter all values");
            }
        }
    }                                           

    private void MineBlockButtonActionPerformed(java.awt.event.ActionEvent evt) {                                                
        // TODO add your handling code here:
        if(nc.isChainValid())
        {
            mined_val = nc.blockchain.get((nc.blockchain.size())-1).mineBlock(4);
            minehash.setText("Hash after mining : "+mined_val);
        }
        else
        {
            minehash.setText("data has been tampered!!! Chain is no more valid!!!");
        }
    }                                               

    private void viewUserButtonActionPerformed(java.awt.event.ActionEvent evt) {                                               
        // TODO add your handling code here:
        nc.viewUser();
        this.setVisible(false);
    }                                              

    private void SubmissionLocActionPerformed(java.awt.event.ActionEvent evt) {                                              
        // TODO add your handling code here:
        loc=SubmissionLoc.getText();
    }                                             

    private void evi_infoActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        evi_det = evi_info.getText();
    }                                        

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {                                       
        // TODO add your handling code here:
        nc.currentUser=0;
        Login log = new Login(nc);
        this.setVisible(false);
        log.setVisible(true);
    }                                      

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomePage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton AddEvidence;
    private javax.swing.JButton MineBlockButton;
    private javax.swing.JTextField SubmissionLoc;
    private javax.swing.JLabel backgroung;
    private javax.swing.JTextField evi_info;
    private javax.swing.JTextField evi_num;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton logout;
    private javax.swing.JTextField minehash;
    private javax.swing.JLabel output;
    private javax.swing.JButton viewUserButton;
    // End of variables declaration                   
    NoobChain nc;
    String loc;
    String evi_det;
    int evi_no;
    String prev_hash;
    String mined_val;
}
