/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cryptoproj;

/**
 *
 * @author SRENIVASS
 */
public class HomePage extends javax.swing.JFrame {

    /**
     * Creates new form HomePage
     */
    public HomePage() {
        initComponents();
    }
    public HomePage(NoobChain n) {
        initComponents();
        nc=n;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        MineBlockButton = new javax.swing.JButton();
        AddEvidence = new javax.swing.JButton();
        viewUserButton = new javax.swing.JButton();
        output = new javax.swing.JLabel();
        SubmissionLoc = new javax.swing.JTextField();
        evi_num = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        evi_info = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel3.setText("Submission Location  :");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(90, 50, 120, 30);

        MineBlockButton.setText("MINE BLOCK");
        MineBlockButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MineBlockButtonActionPerformed(evt);
            }
        });
        jPanel1.add(MineBlockButton);
        MineBlockButton.setBounds(130, 460, 130, 50);

        AddEvidence.setText("ADD EVIDENCE");
        AddEvidence.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddEvidenceActionPerformed(evt);
            }
        });
        jPanel1.add(AddEvidence);
        AddEvidence.setBounds(330, 290, 160, 50);

        viewUserButton.setText("VIEW USER");
        viewUserButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewUserButtonActionPerformed(evt);
            }
        });
        jPanel1.add(viewUserButton);
        viewUserButton.setBounds(400, 460, 120, 50);

        output.setText("ALL DETAILS ABOVE ARE MANDATORY TO ADD EVIDENCE");
        jPanel1.add(output);
        output.setBounds(270, 360, 300, 30);

        SubmissionLoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmissionLocActionPerformed(evt);
            }
        });
        jPanel1.add(SubmissionLoc);
        SubmissionLoc.setBounds(240, 50, 340, 40);

        evi_num.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                evi_numActionPerformed(evt);
            }
        });
        jPanel1.add(evi_num);
        evi_num.setBounds(240, 110, 340, 40);

        jLabel1.setText("Evidence Number   :");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(90, 110, 120, 40);

        jLabel4.setText("Evidence  details      :");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(90, 180, 130, 50);

        evi_info.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                evi_infoActionPerformed(evt);
            }
        });
        jPanel1.add(evi_info);
        evi_info.setBounds(240, 190, 340, 60);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 640, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 536, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>                        

    private void evi_numActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
        evi_no = Integer.parseInt(evi_num.getText());
        System.out.println("took inp");
    }                                       

    private void AddEvidenceActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
        System.out.println("reached here");
        for(int i=0;i<nc.blockchain.size();i++)
        {
            prev_hash = nc.blockchain.get(i).previousHash;
        }
        boolean val=true;
        nc.createBlock(evi_no,nc.currentUser,loc,prev_hash,evi_det);        
            output.setText("evidence added successfully");        
    }                                           

    private void MineBlockButtonActionPerformed(java.awt.event.ActionEvent evt) {                                                
        // TODO add your handling code here:
        mined_val = nc.blockchain.get(0).mineBlock(4);
    }                                               

    private void viewUserButtonActionPerformed(java.awt.event.ActionEvent evt) {                                               
        // TODO add your handling code here:
        nc.viewUser();
    }                                              

    private void SubmissionLocActionPerformed(java.awt.event.ActionEvent evt) {                                              
        // TODO add your handling code here:
        loc=SubmissionLoc.getText();
        System.out.println("took inp");
    }                                             

    private void evi_infoActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        evi_det = evi_info.getText();
        System.out.println("took inp");
    }                                        

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomePage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton AddEvidence;
    private javax.swing.JButton MineBlockButton;
    private javax.swing.JTextField SubmissionLoc;
    private javax.swing.JTextField evi_info;
    private javax.swing.JTextField evi_num;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel output;
    private javax.swing.JButton viewUserButton;
    // End of variables declaration                   
    NoobChain nc;
    String loc;
    String evi_det;
    int evi_no;
    String prev_hash;
    String mined_val;
}
