/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cryptoproj;

import java.util.Random;
import java.util.Scanner;

/**
 *
 * @author SRENIVASS
 */
public class userCheck extends javax.swing.JFrame {

    /**
     * Creates new form userCheck
     */
    public userCheck() {
        initComponents();
    }
    public userCheck(NoobChain n) {
        initComponents();
        nc = n;
        instruction.setText("Choose a random number between 0 and 9 and Please compute h=(2^r)(mod 11) and Enter h");
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        h_val = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        instruction = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        s_val = new javax.swing.JTextField();
        okay = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Constantia", 1, 24)); // NOI18N
        jLabel3.setText("ZKP");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(290, 30, 60, 50);

        h_val.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                h_valActionPerformed(evt);
            }
        });
        jPanel1.add(h_val);
        h_val.setBounds(130, 180, 110, 40);

        instruction.setColumns(20);
        instruction.setRows(5);
        jScrollPane1.setViewportView(instruction);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(60, 96, 500, 70);

        jLabel1.setText("h value:");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(60, 190, 50, 30);

        jLabel2.setText("s value:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(290, 190, 60, 30);

        s_val.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s_valActionPerformed(evt);
            }
        });
        jPanel1.add(s_val);
        s_val.setBounds(370, 180, 90, 40);

        okay.setText("OK");
        okay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okayActionPerformed(evt);
            }
        });
        jPanel1.add(okay);
        okay.setBounds(250, 270, 90, 40);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 619, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 342, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>                        

    private void h_valActionPerformed(java.awt.event.ActionEvent evt) {                                      
        // TODO add your handling code here:
        h = Integer.parseInt(h_val.getText());
        Random rand = new Random();
        b = rand.nextInt(2);
        instruction.setText("Random bit is "+b+"\nPlease compute s=(r+b*x)mod(10).Here x is the number you are proving you know");
    }                                     

    private void s_valActionPerformed(java.awt.event.ActionEvent evt) {                                      
        // TODO add your handling code here:
        s = Integer.parseInt(s_val.getText());
        verifyTransaction(4,9);
    }                                     

    private void okayActionPerformed(java.awt.event.ActionEvent evt) {                                     
        // TODO add your handling code here:
        HomePage hp = new HomePage(nc);
             hp.setVisible(true);
             //hp.output.setText("");
             this.setVisible(false);
    }                                    
    
    public boolean verifyTransaction(int y1,int y2)
    {
        //Random rand = new Random();
        // Scanner sc=new Scanner(System.in);
        System.out.println("\nKindly verify yourself as a user");
        System.out.println("Zero Knowledge Proof");
        System.out.println("Choose a random number between 0 and 9");
        System.out.println("Please compute h=(2^r)(mod 11) and Enter h");
        //int h=sc.nextInt();
        //instruction.setText("Choose a random number between 0 and 9 and Please compute h=(2^r)(mod 11) and Enter h");
        //h =0;
        System.out.println("h is "+ h );
        //int b = rand.nextInt(2);
        System.out.println("Random bit is"+b);
        System.out.println("Please compute s=(r+b*x)mod(10).Here x is the number you are proving you know");
        //instruction.setText("Random bit is "+b+"\nPlease compute s=(r+b*x)mod(10).Here x is the number you are proving you know");
//int s=sc.nextInt();
        //s = Integer.parseInt(s_val.getText());
        int val1=expo(2,s,11);
        int val2=expo(y1,b,11);
        System.out.println("val2 : "+val2);
        val2 = (h*val2)%11;
        int val3=(h*expo(y2,b,11))%11;
        System.out.println("val1 : "+val1);
        System.out.println("val2 : "+val2);
        if(val1==val2)
        {
             System.out.println("Zero Knowledge Proof Successful.You are verified as User 1");
             instruction.setText("Successfully verified and evidence added");
             return true;
        }
        else if(val1==val3)
        {
            System.out.println("Zero Knowledge Proof Successful.You are verified as User 1");
            return true;
        }
        else
        {
            System.out.println("Zero Knowledge Proof Failed.Please try again");
            instruction.setText("Zero Knowledge Proof Failed.Please try again");
            return false;
        }
    }
    int expo(int a,int b,int mod)//(a^b)%mod
    {
        if(b==1)
            return a%mod;
        if(b==0)
            return 1;
        int x=expo(a,b/2,mod);
        x=(x*x)%mod;
        if(b%2==0)
        {
            return x;
        }
        else
        {
            return (x*a)%mod;
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(userCheck.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(userCheck.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(userCheck.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(userCheck.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new userCheck().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JTextField h_val;
    private javax.swing.JTextArea instruction;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton okay;
    private javax.swing.JTextField s_val;
    // End of variables declaration                   
    NoobChain nc;
    int h;
    int s;
    int b;
}
